Fix `max_steps` arg
Farama-Foundation/Minigrid pull request #265
Opened 2022-10-15 19:19 UTC by rodrigodelazcano

# Description

This PR allows to pass the argument `max_steps` when initializing any minigrid environment. `max_steps` indicates the number of environment steps before the episode is truncated.

This PR also fixes issue #264

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-15 22:00 UTC, pseudo-rnd-thoughts requested changes
Looks good, could you make the suggested changes

2022-10-15 22:06 UTC, rodrigodelazcano commented on minigrid/envs/dynamicobstacles.py
> +            max_steps = 4 * size * size
`max_steps=4 * size * size`, was the environments default

2022-10-15 22:06 UTC, rodrigodelazcano commented on minigrid/envs/doorkey.py
> +            max_steps = 10 * size * size
`max_steps=10 * size * size`, was the environments default

2022-10-15 22:10 UTC, rodrigodelazcano commented on tests/test_envs.py
> +    "env_spec", all_testing_env_specs, ids=[spec.id for spec in all_testing_env_specs]
For this PR I also added the possibility of fixing the number of steps with `max_steps`

2022-10-15 22:12 UTC, rodrigodelazcano commented on tests/test_envs.py
> +    env.reset()
I think we should leave it as it is to make sure that the environment is truncated at the specified number of steps. I can reduce the `max_steps` arg to make the test faster. Like to 10

2022-10-15 22:20 UTC, pseudo-rnd-thoughts commented on tests/test_envs.py
> +    env.reset()
Im just worried that there are cases where the agent could accidentally terminate

2022-10-15 22:22 UTC, pseudo-rnd-thoughts commented on tests/test_envs.py
> +    "env_spec", all_testing_env_specs, ids=[spec.id for spec in all_testing_env_specs]
Ohh, ignore me then

2022-10-15 22:22 UTC, pseudo-rnd-thoughts approved these changes

2022-10-15 22:22 UTC, merged

2022-10-16 03:57 UTC, rodrigodelazcano commented on tests/test_envs.py
> +    env.reset()
I'm taking care of this by only stepping with the 'Drop` action. Currently there are no environments that terminate with this action.