Make sure ObstructedMaze is solvable.
Farama-Foundation/Minigrid pull request #334
Opened 2023-03-14 10:43 UTC by SigmaBM

# Description

The blocking ball placed by the `add_door` may cover the box placed on the map by previous `add_door`, causing the agent to be unable to open certain door and unable to complete the task. To make sure this environment solvable, we can first place all the doors and their blocking balls, and then place the keys, so that it ensures that the keys will not be covered by the blocking balls added later.

Fixes # 323

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Screenshots
Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-03-14 11:58 UTC, pseudo-rnd-thoughts requested changes
Could you
1. Provide a test to show the number of environments that are not solvable out of 10,000? 
2. update the version numbers for all Obstructed Maze
3. Add a test to check if the environment is solvable and run 10 times in the tests.

2023-03-19 08:05 UTC, SigmaBM commented
Could you please clarify if "update the version numbers" means changing from "v0" to "v1"? Also, which directory should I place the test files? Thank you.

2023-03-19 11:21 UTC, pseudo-rnd-thoughts commented
> Could you please clarify if "update the version numbers" means changing from "v0" to "v1"? Also, which directory should I place the test files? Thank you.

Yes, just updated the registration version number, see `minigrid/__init__.py` I believe and also update the documentation for the changes from v0 to v1

For testing, could you put it in `tests/test_obstructed_maze.py`

2023-03-19 13:15 UTC, SigmaBM commented
I have updated the version number of related ObstructedMaze envs and the document. A test file is available in `tests/test_obstructed_maze.py`.

2023-03-20 14:48 UTC, pseudo-rnd-thoughts commented on minigrid/envs/obstructedmaze.py
> +    "v1" prevent the key from being covered by the blocking ball.
Could you update to explain why only some of the environments are updated

2023-03-20 14:56 UTC, pseudo-rnd-thoughts requested changes
Could you add a test, `test_solvable_env` that the `env_test` for the v1 envs have a unsolvable == 0

2023-03-21 14:43 UTC, pseudo-rnd-thoughts approved these changes
Thanks, I think this is good.

2023-03-21 14:50 UTC, merged