add babyai bot and test
Farama-Foundation/Minigrid pull request #356
Opened 2023-05-31 18:29 UTC by GilgameshD

# Description

Add the babyai bot from the original babyai repo: https://github.com/mila-iqia/babyai/blob/master/babyai/bot.py
This bot can be used to generate expert demonstrations in all babyai environments.

Fixes # (issue)
https://github.com/Farama-Foundation/Minigrid/issues/308

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-06-09 16:21 UTC, pseudo-rnd-thoughts requested changes

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on minigrid/utils/bot.py
> +class Bot:
As this is for BabyAI only, could we change this name to `BabyAIBot` and change the filename as well to `baby_ai_bot.py`

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on minigrid/utils/bot.py
> +    """The base class for all possible Bot subgoals.
The docstring are all of `NumPy` style I believe, pre-commit checks that docstrings are in `google` style. Could you update

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on tests/test_bot.py
> +    env = gym.make(np.random.choice(babyai_envs), render_mode="human")
Could we `pytest.mark.parameterize` over all BabyAI rather than choose one at random

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on tests/test_bot.py
> +    env.render()
Why do we need to render the environment?

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on tests/test_bot.py
> +    env.render()
Also, using `render_mode="human"`

2023-06-09 16:21 UTC, pseudo-rnd-thoughts commented on tests/test_bot.py
> +def test_bot():
What is the goal of the bot? Do we want the bot to solve every environment within the time limit?

2023-06-09 16:22 UTC, pseudo-rnd-thoughts commented
Hey, thanks for making the PR, looking through the code, could you look at fixing the suggested points

2023-07-12 15:08 UTC, thesofakillers commented
Hey @GilgameshD, are you still working on this?

2023-07-13 03:34 UTC, GilgameshD commented
Sorry, I am distracted by other things. I will go back to finish this PR soon.

2023-07-13 07:26 UTC, thesofakillers commented
Totally get it! I might try taking over and finishing the PR then if that's alright

2023-08-05 12:33 UTC, thesofakillers commented
Can probably close this PR now that #381 is merged :))

2023-08-05 12:54 UTC, closed without merging