NoDeath wrapper
Farama-Foundation/Minigrid pull request #374
Opened 2023-07-04 15:54 UTC by sparisi

New wrapper that prevents death in states like obstacles or lava, and gives an optional negative reward instead.

# Description

The wrapper makes it possible to investigate exploration and safety. 
Making it possible to walk on lava (at a cost) would make exploration more interesting because the agent can find some "aggressive" exploration strategies, like walking over lava to explore as much as possible. This would be a scenario that should be avoided in safe RL.

More discussion here
https://github.com/Farama-Foundation/Minigrid/issues/372

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-07-04 16:05 UTC, sparisi commented
I am not sure why the pre-commit fails. If I run it locally, it failed the first time but succeeded after that.

2023-07-04 20:15 UTC, pseudo-rnd-thoughts requested changes
Could you make these two documentation changes otherwise, looks good to merge to me
@BolunDai0216 Any other comments?

2023-07-04 20:15 UTC, pseudo-rnd-thoughts commented on minigrid/wrappers.py
> +        >>> env = NoDeath(env, ["lava"], -1)
Could you do `no_death_types=("lava",), death_cost=-1.0)` to specify users know what is being specified

2023-07-04 20:15 UTC, pseudo-rnd-thoughts commented on minigrid/wrappers.py
> +        >>> env = NoDeath(env, ["ball"], -1)
`no_death_types=("lava",), death_cost=-1.0`

2023-07-04 21:24 UTC, sparisi commented on minigrid/wrappers.py
> +        >>> env = NoDeath(env, ["ball"], -1)
Done.

2023-07-05 13:41 UTC, pseudo-rnd-thoughts commented
We run doctest in the CI, you need to update `(-1, False)` to `(-1.0, False)`
Run `pytest --doctest gymnasium/` to check there aren't any issues

2023-07-05 14:28 UTC, sparisi commented
> We run doctest in the CI, you need to update `(-1, False)` to `(-1.0, False)` Run `pytest --doctest gymnasium/` to check there aren't any issues

Sorry about that, I am not very familiar with `pytest` and couldn't find where it was failing. Btw, the command was 
`pytest --doctest-modules minigrid/`

Everything seems fine now.

2023-07-05 14:34 UTC, pseudo-rnd-thoughts approved these changes

2023-07-05 14:34 UTC, merged